apiVersion: v1
kind: Service
metadata:
  name: myproject
  namespace: {{ namespace }}
  labels:
    app: myproject
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: myproject